### PR TITLE
Fix: Add the external URL open features 

### LINKED ISSUE #69: Hide AVAILABILITY and PUSH items option the settings menu

### LINKED ISSUE #70: The app should open the website signup page when clicking on "Create a new account" button in the Login page

### PR DESCRIPTION
**Pull request by muhzi4u**
Fixes #69 and Fixes #70

### CODE REVIEW

File: src/screens/Settings/SettingsScreen.js [hunk 1]
```diff
@@ -16,25 +16,28 @@ import images from '../../constants/images';
...
-    iconSize: 'small',
-    itemType: 'toggle',
-  },
-  {
-    text: i18n.t('SETTINGS.PUSH'),
-    checked: false,
-    iconSize: 'small',
-    itemType: 'toggle',
-  },
+  // {
```
Comment (pranavrajs) [inline src/screens/Settings/SettingsScreen.js]: Remove this lines.

Comment (pranavrajs) [reply src/screens/Settings/SettingsScreen.js]: Let us not commented code, if it is not being used, let us remove and re-introduce whenever required.

**Comment by muhzi4u** [comment]
@pranavrajs Please check now
